repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: "19.3b0"
    hooks:
    -   id: black
-   repo: https://github.com/jorisroovers/gitlint
    rev: "v0.15.0"
    hooks:
    -   id: gitlint
